services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_SERVER_HTTP_PORT=2000
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    networks:
      - monitoring
      - proxy
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
      - source: grafana_dashboards_rules
        target: /etc/grafana/provisioning/dashboards/dashboards.yaml
    volumes:
      - grafana:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards/json_files:ro
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M

configs:
  grafana_datasources:
    file: ./configs/datasources.yaml
  grafana_dashboards_rules:
    file: ./configs/dashboards.yaml

volumes:
  grafana:

networks:
  proxy:
    external: true
  monitoring:
    external: true
