services:
  alloy:
    image: grafana/alloy:latest
    user: root
    environment:
      LOKI_HOST: loki
      LOKI_HTTP_PORT: ${LOKI_HTTP_PORT}
      TEMPO_HOST: tempo
      TEMPO_OTLP_GRPC_PORT: ${TEMPO_OTLP_GRPC_PORT}
      ALLOY_OTLP_GRPC_PORT: ${ALLOY_OTLP_GRPC_PORT}
      ALLOY_FARO_PORT: ${ALLOY_FARO_PORT}
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:${ALLOY_UI_PORT}
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    configs:
      - source: alloy_config
        target: /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
configs:
  alloy_config:
    file: ./configs/config.alloy

networks:
  monitoring:
    external: true
