services:
  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - gateway
      - monitoring
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  redis:

networks:
  gateway:
    external: true
  monitoring:
    external: true
