services:
  minio:
    image: quay.io/minio/minio:${MINIO_VERSION:-RELEASE.2024-03-03T17-58-48Z}
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=https://cdn.{$DOMAIN_NAME}
    networks:
      app_net:
      proxy:
      monitoring:
    volumes:
      - ../../data/minio/${ENV_NAME}:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: ${MINIO_MEM_LIMIT:-1G}
      restart_policy:
        condition: on-failure

networks:
  app_net:
    external: true
    name: ${APP_NET}
  proxy:
    external: true
  monitoring:
    external: true
