services:
  caddy:
    image: caddy:2.7-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - proxy
      - monitoring
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /var/www/promo:/var/www/promo:ro
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - MODE_ENV=${MODE_ENV}
      - DOMAIN=${DOMAIN}
      - CDN_BUCKET_NAME=${CDN_BUCKET_NAME}
    configs:
      - source: caddy_conf
        target: /etc/caddy/Caddyfile
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure

volumes:
  caddy_data:
    name: "caddy_data_storage"
  caddy_config:
    name: "caddy_config_storage"

configs:
  caddy_conf:
    file: ./configs/Caddyfile

networks:
  proxy:
    external: true
  monitoring:
    external: true
