services:
  caddy:
    image: caddy:2.7-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    networks:
      - proxy
      - monitoring
    volumes:
      - ../../data/caddy/data:/data
      - ../../data/caddy/config:/config
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - MODE_ENV=${MODE_ENV}
      - DOMAIN=${DOMAIN}
      - CDN_BUCKET_NAME=${CDN_BUCKET_NAME}
    configs:
      - source: caddy_conf
        target: /etc/caddy/Caddyfile
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure

configs:
  caddy_conf:
    file: ./configs/Caddyfile

networks:
  proxy:
    external: true
  monitoring:
    external: true
