apiVersion: 1

groups:
  - name: 'Task Tracker Alerts'
    folder: 'Task Tracker'
    orgId: 1
    type: file
    disableDeletion: false
    editable: true
    options:
      path: /etc/grafana/provisioning/alerting/json_files